/** Sticker art kinds — names match the artwork in each theme pack. */
export const TILE_KINDS = [
  // Edgy
  "crack",
  "doll",
  "flare",
  "crown",
  "smile",
  "alien",
  "dice",
  "pin",
  "spray",
  "bolt",
  "eye",
  "melt",
  "knife",
  "eight",
  "nails",
  "flip",
  "blaze",
  "collar",
  "skull",
  "sting",
  "lock",
  "star",
  "bomb",
  // Anime day (unique / kept)
  "kitty",
  "goggles",
  "butterfly",
  "juice",
  "smirk",
  "kitsune",
  "peace",
  "school",
  "ramen",
  "ember",
  "handheld",
  "katana",
  "bubble",
  "tv",
  "controller",
  "crt",
  "skate",
  "panda",
  "raven",
  "volt",
  "idol",
  "patch",
  "familiar",
  "drake",
  "owl",
  "bot",
  // Anime dark (horror pack)
  "glitch",
  "punk",
  "hood",
  "mask",
  "eyepatch",
  "tears",
  "pill",
  "chain",
  "slime",
  "bunny",
  "candle",
  "crow",
  "bear",
  "poison",
  "heart",
  "hourglass",
  "soda",
  "grimoire",
  // Classroom
  "flame",
  "gem",
  "cans",
  "pizza",
  "rocket",
  "planet",
  "wave",
  "shroom",
  "note",
  "cactus",
  "camera",
  // Doodle creatures
  "jelly",
  "grump",
  "drop",
  "fire",
  "soot",
  "goo",
  "starry",
  "ice",
  "sprout",
  "bee",
  "bun",
  "triple",
  "bat",
  "spook",
  "stalks",
  "cloud",
  "meltblob",
  "bumpy",
  "sheep",
  "night",
  "purr",
  "uni",
  "splash",
  "dino",
  "bow",
  "toad",
  "pebble",
  "rainbow",
  "reaper",
  "king",
  "angel",
  "urchin",
  "swirl",
  "devil",
  // Relic / dark museum pack
  "bust",
  "organ",
  "serpent",
  "dripface",
  "iris",
  "koi",
  "moth",
  "ukiyo",
  "bloom",
  "kabuto",
  "pillar",
  "thunder",
  "regent",
  "rose",
  "shredder",
  "saturn",
  "geode",
  "cortex",
  "wakeup",
  "moon",
  "palm",
  "atlas",
  "omen",
  "vial",
] as const;

export type TileKind = (typeof TILE_KINDS)[number];

/** Edgy pack — razor blade removed; names match art. */
export const EDGY_STICKER_POOL = [
  "crack",
  "doll",
  "flare",
  "crown",
  "smile",
  "alien",
  "dice",
  "pin",
  "spray",
  "bolt",
  "eye",
  "melt",
  "knife",
  "eight",
  "nails",
  "flip",
  "blaze",
  "collar",
  "skull",
  "sting",
  "lock",
  "star",
  "bomb",
] as const satisfies readonly TileKind[];

/** Classroom pack — names match art. */
export const CLASSROOM_STICKER_POOL = [
  "skull",
  "star",
  "flame",
  "heart",
  "gem",
  "bolt",
  "cans",
  "smile",
  "spray",
  "bomb",
  "pizza",
  "rocket",
  "alien",
  "planet",
  "wave",
  "kitty",
  "skate",
  "shroom",
  "note",
  "cactus",
  "camera",
  "peace",
] as const satisfies readonly TileKind[];

/** Anime day pack — names match art. */
export const ANIME_STICKER_POOL = [
  "kitty",
  "goggles",
  "butterfly",
  "juice",
  "smirk",
  "kitsune",
  "peace",
  "school",
  "ramen",
  "ember",
  "handheld",
  "katana",
  "bubble",
  "tv",
  "controller",
  "crt",
  "skate",
  "panda",
  "raven",
  "spray",
  "volt",
  "idol",
  "blaze",
  "patch",
  "familiar",
  "drake",
  "owl",
  "bot",
] as const satisfies readonly TileKind[];

/** Anime dark horror pack — names match art. */
export const ANIME_DARK_STICKER_POOL = [
  "glitch",
  "punk",
  "hood",
  "ramen",
  "mask",
  "katana",
  "eyepatch",
  "tears",
  "butterfly",
  "bolt",
  "pill",
  "chain",
  "slime",
  "bunny",
  "tv",
  "candle",
  "crow",
  "bear",
  "poison",
  "heart",
  "eye",
  "hourglass",
  "soda",
  "grimoire",
] as const satisfies readonly TileKind[];

/** Doodle creature pack — names match art. */
export const DOODLE_STICKER_POOL = [
  "slime",
  "jelly",
  "grump",
  "drop",
  "fire",
  "soot",
  "goo",
  "starry",
  "ice",
  "sprout",
  "bee",
  "bun",
  "triple",
  "bat",
  "spook",
  "stalks",
  "cloud",
  "meltblob",
  "bumpy",
  "sheep",
  "night",
  "purr",
  "uni",
  "splash",
  "dino",
  "bow",
  "toad",
  "pebble",
  "rainbow",
  "reaper",
  "king",
  "angel",
  "urchin",
  "swirl",
  "devil",
] as const satisfies readonly TileKind[];

/** Relic / dark museum pack — names match art. */
export const RELIC_STICKER_POOL = [
  "bust",
  "organ",
  "serpent",
  "dripface",
  "iris",
  "koi",
  "moth",
  "ukiyo",
  "bloom",
  "kabuto",
  "pillar",
  "thunder",
  "regent",
  "rose",
  "shredder",
  "saturn",
  "geode",
  "cortex",
  "wakeup",
  "moon",
  "palm",
  "atlas",
  "omen",
  "vial",
] as const satisfies readonly TileKind[];

/** Unique sticker kinds available for a theme’s chooser / random pick. */
export function stickerPoolForTheme(
  theme: string,
  animeMode: "day" | "dark" = "day",
): readonly TileKind[] {
  if (theme === "classroom") return CLASSROOM_STICKER_POOL;
  if (theme === "doodle") return DOODLE_STICKER_POOL;
  if (theme === "relic") return RELIC_STICKER_POOL;
  if (theme === "anime") {
    return animeMode === "dark" ? ANIME_DARK_STICKER_POOL : ANIME_STICKER_POOL;
  }
  return EDGY_STICKER_POOL;
}

export type FaceStickers = readonly [
  TileKind,
  TileKind,
  TileKind,
  TileKind,
  TileKind,
  TileKind,
];

/**
 * One sticker kind per cube face (F B R L U D).
 * Solved cube = every sticker on a face matches that face’s kind.
 */
export const FACE_STICKERS: FaceStickers = [
  "crack",
  "doll",
  "flare",
  "crown",
  "smile",
  "alien",
];

/** Shuffle a kind pool and take 6 distinct kinds for the six faces. */
export function pickFaceStickers(
  rng: () => number,
  pool: readonly TileKind[] = EDGY_STICKER_POOL,
): FaceStickers {
  const src = pool.length >= 6 ? pool : EDGY_STICKER_POOL;
  const shuffled = src.slice();
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    const tmp = shuffled[i]!;
    shuffled[i] = shuffled[j]!;
    shuffled[j] = tmp;
  }
  return [
    shuffled[0]!,
    shuffled[1]!,
    shuffled[2]!,
    shuffled[3]!,
    shuffled[4]!,
    shuffled[5]!,
  ];
}

export function stickerForColor(
  colorId: number,
  map: readonly TileKind[] = FACE_STICKERS,
): TileKind {
  return map[((colorId % 6) + 6) % 6]!;
}
