/**
 * OCULUM SFX + ambient beds — ElevenLabs Sound Generation.
 * Keep prompts short and Foley-first. Keyword spam makes muddy/harsh clips.
 */
export const SFX_CATALOG = [
  {
    id: "ui-tap",
    file: "ui-tap.mp3",
    duration: 0.5,
    loop: false,
    text: "Soft quiet bronze button tap on wood, warm and clean, very short, gentle game UI click",
  },
  {
    id: "select",
    file: "select.mp3",
    duration: 0.5,
    loop: false,
    text: "Soft parchment card lift, quiet paper rustle, gentle magical sparkle, short clean UI select",
  },
  {
    id: "play",
    file: "play.mp3",
    duration: 0.65,
    loop: false,
    text: "Soft cloth and parchment card placed on stone table, muted thud, quiet wind, short Foley",
  },
  {
    id: "summon",
    file: "summon.mp3",
    duration: 1.15,
    loop: false,
    text: "Premium magical card flip whoosh: thick parchment spins in air with soft wind and a warm low chime, elegant CCG summon, smooth not harsh, no voice",
  },
  {
    id: "site",
    file: "site.mp3",
    duration: 1.0,
    loop: false,
    text: "Heavy carved stone placed on rock, deep soft thud, brief distant temple chime, mystical landmark",
  },
  {
    id: "witness",
    file: "witness.mp3",
    duration: 1.1,
    loop: false,
    text: "Very soft gentle ethereal chime, warm quiet magical unveil, low soft swell, no bright piercing highs, no harsh sparkle, calm beautiful reveal, muted",
  },
  {
    id: "gaze",
    file: "gaze.mp3",
    duration: 0.95,
    loop: false,
    text: "Reverse air inhale through glass, soft mystical whoosh, quiet ring resonance, tense magical steal, smooth",
  },
  {
    id: "graft",
    file: "graft.mp3",
    duration: 0.7,
    loop: false,
    text: "Wood charm click binding to cloth, soft vine settle, short organic Foley attach",
  },
  {
    id: "stance",
    file: "stance.mp3",
    duration: 0.65,
    loop: false,
    text: "Silk cloth whoosh and soft bone click, mask turn, short carnival mystical flip",
  },
  {
    id: "wager",
    file: "wager.mp3",
    duration: 0.7,
    loop: false,
    text: "Soft gold coin placed on velvet, brief carnival chime, Motley ante wager, clean short Foley, no voice",
  },
  {
    id: "cash",
    file: "cash.mp3",
    duration: 0.85,
    loop: false,
    text: "Satisfying coin cascade and warm brass ding, Motley Cash win sting, bright but soft, short triumphant Foley, no voice",
  },
  {
    id: "bust",
    file: "bust.mp3",
    duration: 0.8,
    loop: false,
    text: "Muted coin scatter and soft hollow thud, Motley Bust lose sting, tense short Foley, not harsh, no voice",
  },
  {
    id: "press",
    file: "press.mp3",
    duration: 0.75,
    loop: false,
    text: "Heavy ink stamp pressed into parchment, wet seal thud, Ink Press mark, short dark Foley, clean",
  },
  {
    id: "toll",
    file: "toll.mp3",
    duration: 0.9,
    loop: false,
    text: "Single deep bronze temple bell toll with soft canyon echo, Bellward Toll mark, warm resonant, short, no harsh clang",
  },
  {
    id: "peal",
    file: "peal.mp3",
    duration: 1.0,
    loop: false,
    text: "Soft ringing peal of two bronze bells arming, ascending shimmer, Bellward Peal charge, elegant short sting, no voice",
  },
  {
    id: "rite",
    file: "rite.mp3",
    duration: 1.2,
    loop: false,
    text: "Soft occult whoosh, brief crystal crackle, deep quiet void bloom, single muted bronze bell, eerie magical spell",
  },
  {
    id: "pass",
    file: "pass.mp3",
    duration: 0.5,
    loop: false,
    text: "Soft stone seal closing, quiet breath, calm short turn-end click",
  },
  {
    id: "resolve",
    file: "resolve.mp3",
    duration: 1.1,
    loop: false,
    text: "Deep soft canyon impact, muted war drum hit, brief glass crack, powerful clean combat sting, not muddy",
  },
  {
    id: "law",
    file: "law.mp3",
    duration: 1.0,
    loop: false,
    text: "Sacred decree sting, soft choir and bronze gong, short mystical triumph, clear and warm",
  },
  {
    id: "eclipse",
    file: "eclipse.mp3",
    duration: 1.05,
    loop: false,
    text: "Low celestial hum as a dark sun closes, soft pulse, ominous beautiful omen sting, smooth",
  },
  {
    id: "stain",
    file: "stain.mp3",
    duration: 0.75,
    loop: false,
    text: "Wet ink drip on parchment, soft viscous splat, short eerie resonance, clean Foley",
  },
  {
    id: "strain",
    file: "strain.mp3",
    duration: 0.8,
    loop: false,
    text: "Soft fibrous crack and strained breath, short tense wound hit, mystical not gory",
  },
  {
    id: "blind",
    file: "blind.mp3",
    duration: 0.75,
    loop: false,
    text: "Candle snuffed in mist, soft hollow whoosh, muted extinguish, short quiet",
  },
  {
    id: "draw",
    file: "draw.mp3",
    duration: 0.5,
    loop: false,
    text: "Soft parchment slide from a deck, tiny quiet sparkle, very short clean card draw",
  },
  {
    id: "fall",
    file: "fall.mp3",
    duration: 1.2,
    loop: false,
    text: "Soft ash dissolve and distant hollow impact, truncated ethereal cry, dramatic card death, not harsh",
  },
  {
    id: "win",
    file: "win.mp3",
    duration: 3.5,
    loop: false,
    text: "Triumphant soft war drums and warm brass swell with gentle choir, short victory fanfare, epic but smooth, no lyrics",
  },
  {
    id: "lose",
    file: "lose.mp3",
    duration: 3.2,
    loop: false,
    text: "Solemn hollow wind, soft mourning choir, distant cracked bell, tragic short defeat sting, no lyrics",
  },
  {
    id: "enemy",
    file: "enemy.mp3",
    duration: 0.55,
    loop: false,
    text: "Soft low distant breath and quiet dark chime, short turn cue, gentle",
  },
  {
    id: "music-menu",
    file: "music-menu.mp3",
    duration: 22,
    loop: true,
    // Intentionally not regenerated — Ashen Keep beds are hand-picked; do not overwrite with SFX API.
    text: "DO NOT REGEN — use committed Ashen Keep menu bed",
    skipGenerate: true,
  },
  {
    id: "music-match",
    file: "music-match.mp3",
    duration: 24,
    loop: true,
    text: "DO NOT REGEN — use committed Ashen Keep match bed",
    skipGenerate: true,
  },
  {
    id: "music-victory",
    file: "music-victory.mp3",
    duration: 14,
    loop: true,
    text: "DO NOT REGEN — use committed victory bed",
    skipGenerate: true,
  },
  {
    id: "music-defeat",
    file: "music-defeat.mp3",
    duration: 14,
    loop: true,
    text: "DO NOT REGEN — use committed defeat bed",
    skipGenerate: true,
  },
];
