/**
 * OCULUM premium RPG SFX + ambient beds — ElevenLabs Sound Generation.
 * Generated offline, shipped as static mp3 under public/sfx/.
 */
export const SFX_CATALOG = [
  {
    id: "ui-tap",
    file: "ui-tap.mp3",
    duration: 0.4,
    loop: false,
    text: "Premium dark fantasy RPG UI tap: soft deep wood and bronze ritual click, warm quiet chime, polished AAA game interface, short clean, no plastic, no sci-fi beep, no cartoon",
  },
  {
    id: "select",
    file: "select.mp3",
    duration: 0.45,
    loop: false,
    text: "Premium dark fantasy RPG card select: gentle parchment lift with a soft ethereal eye shimmer, warm mystical UI pick, short polished AAA game sound, no plastic, no cyber",
  },
  {
    id: "play",
    file: "play.mp3",
    duration: 0.65,
    loop: false,
    text: "Premium dark fantasy RPG card play onto stone table: soft heavy parchment place with distant canyon wind whisper, mystical veiled presence landing, polished AAA game Foley, short",
  },
  {
    id: "witness",
    file: "witness.mp3",
    duration: 1.1,
    loop: false,
    text: "Premium dark fantasy RPG revelation: deep resonant eye-opening choir swell with crystalline Sight spark and soft temple bell, magical unveil moment, polished AAA, emotional, not harsh",
  },
  {
    id: "gaze",
    file: "gaze.mp3",
    duration: 1.0,
    loop: false,
    text: "Premium dark fantasy RPG stolen gaze: reverse ethereal inhale, ring-eye vortex whoosh, mysterious revelation theft, polished AAA mystical combat UI, tense and beautiful",
  },
  {
    id: "graft",
    file: "graft.mp3",
    duration: 0.7,
    loop: false,
    text: "Premium dark fantasy RPG relic graft: wooden root and metal charm binding click with soft organic vine settle, mystical attachment Foley, polished AAA short",
  },
  {
    id: "stance",
    file: "stance.mp3",
    duration: 0.65,
    loop: false,
    text: "Premium dark fantasy RPG stance flip: three-face mask turn with soft bone and silk whoosh, mystical power swap, polished AAA short",
  },
  {
    id: "rite",
    file: "rite.mp3",
    duration: 0.85,
    loop: false,
    text: "Premium dark fantasy RPG rite blind: hollow pale silence bloom, soft void hush and ash-lantern extinguish, mystical altitude blind, polished AAA",
  },
  {
    id: "pass",
    file: "pass.mp3",
    duration: 0.45,
    loop: false,
    text: "Premium dark fantasy RPG end turn: soft stone seal close and quiet breath, polished AAA UI pass, short and clean",
  },
  {
    id: "resolve",
    file: "resolve.mp3",
    duration: 1.2,
    loop: false,
    text: "Premium dark fantasy RPG altitude resolve: deep canyon cliff impact with distant war drum and ethereal Will crack, polished AAA combat payoff, powerful but not muddy",
  },
  {
    id: "law",
    file: "law.mp3",
    duration: 1.1,
    loop: false,
    text: "Premium dark fantasy RPG prophecy law: sacred unblinking decree, layered choir and eclipse bronze gong, polished AAA mystical triumph sting",
  },
  {
    id: "eclipse",
    file: "eclipse.mp3",
    duration: 1.15,
    loop: false,
    text: "Premium dark fantasy RPG eclipse gain: dark sun occlude with low celestial hum and faint eye pulse, polished AAA ominous reward",
  },
  {
    id: "win",
    file: "win.mp3",
    duration: 1.8,
    loop: false,
    text: "Premium dark fantasy RPG ascend victory: rising canyon choir, golden eye radiance, triumphant but solemn AAA game win sting, no chiptune",
  },
  {
    id: "lose",
    file: "lose.mp3",
    duration: 1.5,
    loop: false,
    text: "Premium dark fantasy RPG break defeat: Will shatter soft glass and distant wind through empty cliffs, solemn AAA lose sting, emotional not cartoon",
  },
  {
    id: "enemy",
    file: "enemy.mp3",
    duration: 0.55,
    loop: false,
    text: "Premium dark fantasy RPG enemy turn cue: low distant rival breath and soft dark chime, polished AAA turn banner, short",
  },
  {
    id: "music-menu",
    file: "music-menu.mp3",
    duration: 22,
    loop: true,
    text: "Seamless looping premium dark fantasy RPG menu ambience: deep canyon wind, distant temple drones, soft low choir pads, mystical eye-cult atmosphere, cinematic AAA game menu music bed, no melody hooks, no vocals with lyrics, calm and immersive",
  },
  {
    id: "music-match",
    file: "music-match.mp3",
    duration: 24,
    loop: true,
    text: "Seamless looping premium dark fantasy RPG match ambience: tense canyon wind, soft war drums far away, mystical Sight drones, polished AAA card battler combat bed, atmospheric not busy, no lyrics, immersive",
  },
];
