/**
 * OCULUM premium RPG SFX + ambient beds — ElevenLabs Sound Generation.
 * Generated offline, shipped as static mp3 under public/sfx/.
 */
export const SFX_CATALOG = [
  {
    id: "ui-tap",
    file: "ui-tap.mp3",
    duration: 0.4,
    loop: false,
    text: "Premium dark fantasy RPG UI tap: soft deep wood and bronze ritual click, warm quiet chime, polished AAA game interface, short clean, no plastic, no sci-fi beep, no cartoon",
  },
  {
    id: "select",
    file: "select.mp3",
    duration: 0.45,
    loop: false,
    text: "Premium dark fantasy RPG card select: gentle parchment lift with a soft ethereal eye shimmer, warm mystical UI pick, short polished AAA game sound, no plastic, no cyber",
  },
  {
    id: "play",
    file: "play.mp3",
    duration: 0.65,
    loop: false,
    text: "Premium dark fantasy RPG card play onto stone table: soft heavy parchment place with distant canyon wind whisper, mystical veiled presence landing, polished AAA game Foley, short",
  },
  {
    id: "site",
    file: "site.mp3",
    duration: 1.15,
    loop: false,
    text: "Premium dark fantasy RPG landmark site planted: heavy carved stone shrine settling into canyon rock, deep resonant foundation thud, soft ethereal eye-seal chime bloom, sacred architecture awakening, polished AAA CCG site placement, weighty mystical, no lyrics, no comedy, no chiptune",
  },
  {
    id: "witness",
    file: "witness.mp3",
    duration: 1.1,
    loop: false,
    text: "Premium dark fantasy RPG revelation: deep resonant eye-opening choir swell with crystalline Sight spark and soft temple bell, magical unveil moment, polished AAA, emotional, not harsh",
  },
  {
    id: "gaze",
    file: "gaze.mp3",
    duration: 1.0,
    loop: false,
    text: "Premium dark fantasy RPG stolen gaze: reverse ethereal inhale, ring-eye vortex whoosh, mysterious revelation theft, polished AAA mystical combat UI, tense and beautiful",
  },
  {
    id: "graft",
    file: "graft.mp3",
    duration: 0.7,
    loop: false,
    text: "Premium dark fantasy RPG relic graft: wooden root and metal charm binding click with soft organic vine settle, mystical attachment Foley, polished AAA short",
  },
  {
    id: "stance",
    file: "stance.mp3",
    duration: 0.65,
    loop: false,
    text: "Premium dark fantasy RPG stance flip: three-face mask turn with soft bone and silk whoosh, mystical power swap, polished AAA short",
  },
  {
    id: "rite",
    file: "rite.mp3",
    duration: 1.6,
    loop: false,
    text: "Dark fantasy spell cast SFX: sharp occult incantation whoosh, crystalline eye-sigil shatter, deep void bloom, short bronze bell strike, premium AAA CCG rite/spell activation, magical and eerie, no melody song, no lyrics, no comedy, no chiptune, no UI click",
  },
  {
    id: "pass",
    file: "pass.mp3",
    duration: 0.45,
    loop: false,
    text: "Premium dark fantasy RPG end turn: soft stone seal close and quiet breath, polished AAA UI pass, short and clean",
  },
  {
    id: "resolve",
    file: "resolve.mp3",
    duration: 1.2,
    loop: false,
    text: "Premium dark fantasy RPG altitude resolve: deep canyon cliff impact with distant war drum and ethereal Will crack, polished AAA combat payoff, powerful but not muddy",
  },
  {
    id: "law",
    file: "law.mp3",
    duration: 1.1,
    loop: false,
    text: "Premium dark fantasy RPG prophecy law: sacred unblinking decree, layered choir and eclipse bronze gong, polished AAA mystical triumph sting",
  },
  {
    id: "eclipse",
    file: "eclipse.mp3",
    duration: 1.15,
    loop: false,
    text: "Premium dark fantasy RPG eclipse gain: dark sun occlude with low celestial hum and faint eye pulse, polished AAA ominous reward",
  },
  {
    id: "win",
    file: "win.mp3",
    duration: 3.8,
    loop: false,
    text: "Best premium dark fantasy CCG victory fanfare: 4-second triumphant Ascend theme with canyon war drums, golden brass horns, rising sacred choir, radiant eye-faith resolve, epic exhilarating dark mystical melody hook, AAA quality, no lyrics, no comedy, no chiptune",
  },
  {
    id: "lose",
    file: "lose.mp3",
    duration: 3.4,
    loop: false,
    text: "Best premium dark fantasy CCG defeat theme: 3-second solemn Sight Lost sting with shattered Will glass, hollow canyon wind, low mourning choir, distant broken temple bell, emotional tragic weight, AAA quality, no lyrics, no comedy, no chiptune",
  },
  {
    id: "fall",
    file: "fall.mp3",
    duration: 1.35,
    loop: false,
    text: "Premium dark fantasy RPG death Unmake: figure dissolves into ash and void dust, deep bone crack, ethereal scream truncated, canyon echo of falling body erased from Sight, polished AAA CCG card death, dramatic and final, no comedy, no chiptune",
  },
  {
    id: "enemy",
    file: "enemy.mp3",
    duration: 0.55,
    loop: false,
    text: "Premium dark fantasy RPG enemy turn cue: low distant rival breath and soft dark chime, polished AAA turn banner, short",
  },
  {
    id: "music-menu",
    file: "music-menu.mp3",
    duration: 22,
    loop: true,
    text: "Seamless looping premium dark fantasy RPG menu ambience: deep canyon wind, distant temple drones, soft low choir pads, mystical eye-cult atmosphere, cinematic AAA game menu music bed, no melody hooks, no vocals with lyrics, calm and immersive",
  },
  {
    id: "music-match",
    file: "music-match.mp3",
    duration: 24,
    loop: true,
    text: "Seamless looping premium dark fantasy RPG match ambience: tense canyon wind, soft war drums far away, mystical Sight drones, polished AAA card battler combat bed, atmospheric not busy, no lyrics, immersive",
  },
  {
    id: "music-victory",
    file: "music-victory.mp3",
    duration: 14,
    loop: true,
    text: "Seamless looping premium dark fantasy victory music bed: triumphant but solemn Ascend atmosphere, warm golden canyon horns pads, soft sacred choir, slow proud war drum pulse, eye-faith radiance, cinematic AAA CCG win screen music, immersive emotional, no lyrics, no comedy, no chiptune",
  },
  {
    id: "music-defeat",
    file: "music-defeat.mp3",
    duration: 14,
    loop: true,
    text: "Seamless looping premium dark fantasy defeat music bed: mournful Sight Lost atmosphere, hollow canyon wind, low broken choir drones, distant cracked temple bells, cold empty cliffs, cinematic AAA CCG lose screen music, heavy emotional weight, no lyrics, no comedy, no chiptune",
  },
];
