import type { CardDef } from "./types";

/**
 * Bonewick — Wave 1 (Vessel craft soft reboot).
 * Continuity via Inhabitant; Fall refill Veiled; Eclipse-light; Mid only with Vessel.
 * Art: coastal bone shrine / Bone Gallery DNA.
 * Names: Bonewick-native only — no ash/ember, no cross-craft Widow/Cantor/Sovereign clones.
 */
export const BONEWICK_WAVE1: CardDef[] = [
  {
    id: "wick_walker",
    name: "Wick Walker",
    heresy: "shell",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject:
      "wick walker one-eye cracked bone-white construct coastal bone shrine royal blue eye-banners pale sea NO hat original Bonewick",
    veiledAbility: "When this Holds: if you control a Vessel, gain 1 Sight.",
    revelation: "If you control a Vessel, gain 1 Sight. If an Inhabitant exists anywhere, draw 1.",
    text: "Veiled: When this Holds: if you control a Vessel, gain 1 Sight. Revelation: If you control a Vessel, gain 1 Sight. If an Inhabitant exists anywhere, draw 1.",
  },
  {
    id: "salt_veil",
    name: "Salt Veil",
    heresy: "shell",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject:
      "salt veil cracked bone-white ceramic figure salt-spray veil coastal bone shrine blue shards sparingly glamorous original Bonewick",
    veiledAbility: "While Veiled: +1 power if you control a Vessel.",
    revelation: "If you control Bone Gallery, draw 1. If you control a Vessel, gain 1 Sight.",
    text: "Veiled: While Veiled: +1 power if you control a Vessel. Revelation: If you control Bone Gallery, draw 1. If you control a Vessel, gain 1 Sight.",
  },
  {
    id: "midwick_voice",
    name: "Midwick Voice",
    heresy: "shell",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 1,
    witnessedPower: 3,
    sightYield: 0,
    artSubject:
      "midwick voice one-eye bone construct mid dock coastal bone shrine blue banners NO dusk hat original Bonewick",
    veiledAbility: "When this wins Resolve while Veiled: if on Mid and you control a Vessel, gain 1 Sight.",
    revelation: "If on Mid and you control a Vessel, draw 1. Otherwise gain 1 Sight.",
    text: "Veiled: When this wins Resolve while Veiled: if on Mid and you control a Vessel, gain 1 Sight. Revelation: If on Mid and you control a Vessel, draw 1. Otherwise gain 1 Sight.",
  },
  {
    id: "shard_walker",
    name: "Shard Walker",
    heresy: "shell",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 2,
    sightYield: 1,
    artSubject:
      "shard walker cracked bone mask blue shard charms coastal bone shrine staff original Bonewick",
    veiledAbility: "While Veiled: +1 power if you control a Vessel with no Inhabitant.",
    revelation: "If you control a Vessel with no Inhabitant, gain 1 Sight.",
    text: "Veiled: While Veiled: +1 power if you control a Vessel with no Inhabitant. Revelation: If you control a Vessel with no Inhabitant, gain 1 Sight. While Witnessed: +1 Sight/turn.",
  },
  {
    id: "wick_throne",
    name: "Wick Throne",
    heresy: "shell",
    type: "figure",
    essence: 5,
    witnessCost: 3,
    veiledPower: 3,
    witnessedPower: 6,
    sightYield: 0,
    sovereign: true,
    artSubject:
      "wick throne cracked bone throne one-eye sovereign coastal bone shrine blue banners premium original Bonewick",
    text: "Revelation: Tuck a Figure from hand into a friendly Vessel if able. Fall: draw 1. While Witnessed: your Vessels have +1 power.",
  },
  {
    id: "bone_gallery",
    name: "Bone Gallery",
    heresy: "shell",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 1,
    artSubject:
      "bone gallery coastal bone shrine cracked relics eye banners low tide landmark original Bonewick",
    text: "Site. +1 Sight/turn. When you Witness a Bonewick Figure here, gain 1 Sight. Your Veiled Vessels here have +1 power.",
  },
  {
    id: "shard_cache",
    name: "Shard Cache",
    heresy: "shell",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject:
      "shard cache coastal bone crates blue shard ofuda low tide landmark original Bonewick",
    text: "Site. When a friendly Vessel Falls here, draw 1.",
  },
  {
    id: "inhabit_charm",
    name: "Inhabit Charm",
    heresy: "shell",
    type: "relic",
    essence: 1,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject:
      "inhabit charm bone wick pendant blue shard coastal relic original Bonewick",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, if you have an Inhabitant, gain 1 Sight.",
  },
  {
    id: "wick_charm",
    name: "Wick Charm",
    heresy: "shell",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject:
      "wick charm amber wick bone charm blue cord coastal relic original Bonewick",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, if you control a Vessel, draw 1.",
  },
  {
    id: "wick_tithe",
    name: "Wick Tithe",
    heresy: "shell",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject:
      "wick tithe rite bone staff coastal bone shrine blue banners original Bonewick",
    text: "If you have an Inhabitant, draw 1 and gain 1 Sight. Otherwise gain 1 Sight.",
  },
  {
    id: "shell_tithe",
    name: "Shell Tithe",
    heresy: "shell",
    type: "rite",
    essence: 1,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject:
      "shell tithe rite bone shell seal coastal shrine blue banners original Bonewick",
    text: "If you control a Vessel, draw 1. Otherwise gain 1 Sight.",
  },
  {
    id: "bone_urn",
    name: "Bone Urn",
    heresy: "shell",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject:
      "bone urn cracked bone-white vessel one-eye interior coastal bone shrine original Bonewick",
    text: "Vessel. Tucks a Figure from hand if able. Fall: release Inhabitant here Veiled. Revelation: release Inhabitant here Veiled if empty, else to hand. If you control Bone Gallery, gain 1 Sight.",
  },
  {
    id: "bone_lantern",
    name: "Bone Lantern",
    heresy: "shell",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 3,
    sightYield: 0,
    artSubject:
      "bone lantern cracked bone lantern-vessel pale wick coastal shrine blue shards original Bonewick",
    text: "Vessel. Tucks a Figure from hand if able. Fall: release Inhabitant here Veiled; if you control another Vessel, gain 1 Sight. Revelation: release Inhabitant here Veiled if empty, else to hand.",
  },
];

export const BONEWICK_WAVE1_RITE_IDS = new Set(["wick_tithe", "shell_tithe"]);
