import type { CardDef } from "./types";

export const CARDS: CardDef[] = [
  {
    id: "cliff_seeker",
    name: "Cliff Seeker",
    school: "cube",
    type: "figure",
    essence: 1,
    witnessCost: 1,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject: "desert cliff wanderer geometric cube-mask teal sash eye-glyph banners",
    text: "Revelation: Gain 1 Sight. Witnessed: +1 Sight/turn.",
  },
  {
    id: "veil_banner",
    name: "Veil Banner",
    school: "cube",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "tattered cliff mast banner eye-in-circle glyph rope bridges",
    text: "Site. Your Veiled Figures here get +1 power.",
  },
  {
    id: "ace_of_hollows",
    name: "Ace of Hollows",
    school: "deal",
    type: "relic",
    essence: 1,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject: "ornate floating playing-card relic eye-diamond back purple gold",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, draw 1.",
  },
  {
    id: "hatline_trickster",
    name: "Hatline Trickster",
    school: "deal",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject: "skull-mask gambler mystic card-rim hat purple coat canyon sunset",
    text: "Revelation: Bounce a Veiled board card to its owner's hand.",
  },
  {
    id: "third_face",
    name: "Third Face",
    school: "many",
    type: "sigil",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "three-face spirit seal plaque horns chains tree sigil",
    text: "Sigil. Once/turn: switch Stance on a friendly Figure here.",
  },
  {
    id: "root_chassis",
    name: "Root Chassis",
    school: "graft",
    type: "figure",
    essence: 2,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 0,
    sightYield: 2,
    artSubject: "wood-rooted white golem cyan lenses redwood forest reclamation",
    text: "Revelation: Become site-hybrid — power 0, +2 Sight/turn.",
  },
  {
    id: "hole_choir",
    name: "Hole Choir",
    school: "hollow",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "hole-headed clergy silhouette glyph sash canyon twilight ritual",
    text: "Blind an altitude this turn. Draw 1.",
  },
  {
    id: "coral_crown",
    name: "Coral Crown",
    school: "coral",
    type: "relic",
    essence: 3,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject: "coral antler crown stylized eye glyphs teal cloth arid pillars",
    text: "Graft: +1 power while host Witnessed. Host altitude gains Gaze.",
  },
  {
    id: "ribcity_angel",
    name: "Ribcity Angel",
    school: "shell",
    type: "vessel",
    essence: 4,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 1,
    artSubject: "cracked ceramic angel one iridescent eye miniature city in chest",
    text: "Vessel. Tucks a Figure from hand if able. Revelation: release Inhabitant here if empty, else to hand.",
  },
  {
    id: "depth_matron",
    name: "Depth Matron",
    school: "deep",
    type: "figure",
    essence: 5,
    witnessCost: 3,
    veiledPower: 3,
    witnessedPower: 6,
    sightYield: 1,
    artSubject: "four-armed blue seer multi-eye crown jungle ruins waterfalls gold gems",
    text: "Revelation: Freely Witness your other Veiled Figures/Vessels (their Revelations do not fire).",
  },
  {
    id: "ring_gaze",
    name: "Ring Gaze",
    school: "ring",
    type: "site",
    essence: 3,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 1,
    artSubject: "rotating ring-eye temple landmark purple banners coastal cliffs",
    text: "Site with Gaze. +1 Sight/turn (+2 on High).",
  },
  {
    id: "unblinking_law",
    name: "Unblinking Law",
    school: "neutral",
    type: "prophecy",
    essence: 0,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "abstract law tablet eye-staff seal floating purple shards",
    text: "Prophecy (on Pass): Witness 3 schools in one turn → +2 Eclipse.",
  },
  {
    id: "stake_field_pilgrim",
    name: "Stake Field Pilgrim",
    school: "cube",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "ochre-robed pilgrim four-hole wood mask staff barren stake field pale sky",
    text: "Revelation: If no enemy unit here, gain 1 Eclipse.",
  },
  {
    id: "branch_rune_reliquary",
    name: "Branch-Rune Reliquary",
    school: "coral",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 1,
    artSubject: "oval stone talisman red branch-rune hanging red ribbons barren stakes",
    text: "Site. +1 Sight/turn. Your Witnessed Figures here get +1 power.",
  },
  {
    id: "perforated_abbess",
    name: "Perforated Abbess",
    school: "hollow",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject: "gaunt hollow clergy bone mask multi-apertures orange cloak circular cutouts",
    text: "Witnessed: +1 Sight/turn. This altitude has Gaze while she is Witnessed.",
  },
  {
    id: "keywright_scarecrow",
    name: "Keywright Scarecrow",
    school: "graft",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "patchwork scarecrow windmill-sail crown oversized brass key green hills",
    text: "Revelation: Draw 1. If you have a Site here, gain 1 Sight.",
  },
  {
    id: "parasol_path",
    name: "Parasol Path",
    school: "ring",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 1,
    artSubject: "red parasol cliff waypoint bells white banners eye seals coastal heights",
    text: "Site with Gaze. +1 Sight/turn (+2 on High).",
  },
  {
    id: "ochre_vanguard",
    name: "Ochre Vanguard",
    school: "deal",
    type: "figure",
    essence: 4,
    witnessCost: 2,
    veiledPower: 3,
    witnessedPower: 5,
    sightYield: 0,
    artSubject: "solemn ochre-armored surreal vanguard battered plate eye-seal banner desert",
    text: "Revelation: Gain 1 Eclipse.",
  },
  {
    id: "echo_mask",
    name: "Echo Mask",
    school: "many",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "twin-face wooden mask spirit hanging charms forest perch teal cloth",
    text: "Revelation: Switch Stance on another friendly Figure.",
  },
  {
    id: "bone_wick_charm",
    name: "Bone-Wick Charm",
    school: "shell",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject: "cracked ceramic charm wick-flame eye seal hanging ofuda",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, gain 1 Sight.",
  },
  {
    id: "low_tide_shrine",
    name: "Low-Tide Shrine",
    school: "shell",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "coastal shrine low tide exposed bone pillars eye banners",
    text: "Site. Your Veiled Vessels here get +1 power.",
  },
  {
    id: "pale_silence",
    name: "Pale Silence",
    school: "hollow",
    type: "rite",
    essence: 1,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "hollow rite gesture pale void sash barren arches no choir",
    text: "Blind an altitude this turn.",
  },
  {
    id: "ledger_jackal",
    name: "Ledger Jackal",
    school: "deal",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "jackal-mask gambler ledger scrolls canyon dusk purple coat",
    text: "Revelation: If you have Eclipse, draw 1.",
  },
  {
    id: "iris_heliograph",
    name: "Iris Heliograph",
    school: "ring",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 4,
    sightYield: 1,
    artSubject: "ring-priest mirror iris apparatus coastal cliff sunlight seals",
    text: "Witnessed: +1 Sight/turn. This altitude has Gaze while Witnessed. When you Witness an enemy here, gain 1 Eclipse.",
    premium: true,
  },
  {
    id: "verdant_cataract",
    name: "Verdant Cataract",
    school: "deep",
    type: "figure",
    essence: 4,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 5,
    sightYield: 1,
    artSubject: "immense jungle waterfall seer moss crown multi-limb green gold",
    text: "Revelation: Gain 1 Sight per your Witnessed Figure (max 3). While Witnessed: your other Figures have +1 power.",
    premium: true,
  },
  {
    id: "split_gaze_seraph",
    name: "Split-Gaze Seraph",
    school: "many",
    type: "figure",
    essence: 5,
    witnessCost: 3,
    veiledPower: 3,
    witnessedPower: 6,
    sightYield: 1,
    artSubject: "many-faced seraph horn chains split masks tree canopy gold violet",
    text: "Revelation: Switch Stance on all your other Figures. If 2+ of your Figures are Stance B, gain 1 Eclipse.",
    premium: true,
  },
  {
    id: "saltglass_courier",
    name: "Saltglass Courier",
    school: "cube",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "desert scavenger orange perforated hat charm belts companion hound visor canyon antennas",
    text: "Revelation: If on High, draw 1.",
  },
  {
    id: "pillar_cantor",
    name: "Pillar Cantor",
    school: "coral",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject: "coral-pillar chanter red branch-rune sash arid stone tablets hanging ribbons",
    text: "Revelation: If you have a Site here, gain 1 Eclipse.",
  },
  {
    id: "canister_hound",
    name: "Canister Hound",
    school: "graft",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "lean mechanical-visor hound orange harness canister windmill hills cyan optics",
    text: "Revelation: If you control another Graft card, draw 1.",
  },
  {
    id: "inkdrip_acolyte",
    name: "Inkdrip Acolyte",
    school: "hollow",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 1,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "pale ink-maw pilgrim cream dress black drip wings swamp one-eye shades",
    text: "Revelation: Blind this altitude this turn.",
  },
  {
    id: "ash_lantern",
    name: "Ash Lantern",
    school: "shell",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject: "cracked ceramic lantern-vessel ember eye interior shrine path bone pillars",
    text: "Vessel. Tucks a Figure from hand if able. Revelation: release Inhabitant here if empty, else to hand.",
  },
  {
    id: "mire_debtor",
    name: "Mire Debtor",
    school: "deep",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 1,
    witnessedPower: 3,
    sightYield: 1,
    artSubject: "jungle ruin debtor moss cords multi-eye charms waterfall stairs teal cloth",
    text: "Revelation: Gain 1 Sight. Witnessed: +1 Sight/turn.",
  },
  {
    id: "twinspoke_banner",
    name: "Twinspoke Banner",
    school: "many",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "twin-face banner tree perch split masks teal red cloth hanging charms",
    text: "Site. When you switch Stance on a Figure here, gain 1 Sight.",
  },
  {
    id: "dust_ledger",
    name: "Dust Ledger",
    school: "deal",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 1,
    artSubject: "canyon gambling shrine dusty ledger banners purple gold eye seals",
    text: "Site. +1 Sight/turn. Your Witnessed Deal Figures here get +1 power.",
  },
  {
    id: "pale_arch",
    name: "Pale Arch",
    school: "hollow",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 1,
    artSubject: "barren pale stone arch circular cutouts orange void banners hollow clergy",
    text: "Site. +1 Sight/turn. Your Witnessed Hollow Figures here get +1 power.",
  },
  {
    id: "suture_mill",
    name: "Suture Mill",
    school: "graft",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "wood-metal windmill suture workshop cyan optics green hills patchwork sails",
    text: "Site. Your Veiled Graft Figures here get +1 power.",
  },
  {
    id: "bell_debt_walker",
    name: "Bell-Debt Walker",
    school: "ring",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "coastal cliff walker red parasol bells white banners eye-seal path",
    text: "Revelation: If you control a Gaze altitude, gain 1 Sight.",
  },
  {
    id: "shard_pilgrim",
    name: "Shard Pilgrim",
    school: "shell",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 2,
    sightYield: 1,
    artSubject: "ceramic-shard pilgrim cracked mask ember charms coastal bone shrine",
    text: "Revelation: If you have a Vessel in play, gain 1 Sight. Witnessed: +1 Sight/turn.",
  },
  {
    id: "ribbon_tithe",
    name: "Ribbon Tithe",
    school: "coral",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "coral rite hands red branch-ribbons arid pillars hanging talismans",
    text: "Blind an altitude this turn. If you control a Coral card, draw 1.",
  },
  {
    id: "stake_sovereign",
    name: "Stake Sovereign",
    school: "cube",
    type: "figure",
    essence: 4,
    witnessCost: 2,
    veiledPower: 3,
    witnessedPower: 5,
    sightYield: 0,
    artSubject: "ochre sovereign four-hole wood mask stake field pale sky red ribbons staff",
    text: "Revelation: Gain 1 Eclipse. While Witnessed: your other Veiled Figures have +1 power.",
    premium: true,
  },
  {
    id: "abyss_cairn",
    name: "Abyss Cairn",
    school: "deep",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 1,
    artSubject: "jungle ruin cairn moss stones waterfall teal banners multi-eye seals",
    text: "Site. +1 Sight/turn. Your Witnessed Deep Figures here get +1 power.",
  },
  {
    id: "stake_cache",
    name: "Stake Cache",
    school: "cube",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "barren stake cache ochre crates eye-glyph banners pale desert sky",
    text: "Site. When you Witness a Cube Figure here, gain 1 Sight.",
  },
  {
    id: "debt_coin",
    name: "Debt Coin",
    school: "deal",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject: "ornate gambling coin relic purple gold eye-diamond canyon dusk",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, if you have Eclipse, gain 1 Sight.",
  },
  {
    id: "splice_token",
    name: "Splice Token",
    school: "graft",
    type: "relic",
    essence: 1,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject: "brass splice token cyan optics windmill patchwork charm",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, if you have a Graft Site, draw 1.",
  },
  {
    id: "hornchain_debtor",
    name: "Hornchain Debtor",
    school: "many",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject: "horn-chain twin-mask debtor tree perch teal cloth hanging charms",
    text: "Revelation: Switch Stance on this Figure. If it is Stance B after, gain 1 Sight.",
  },
  {
    id: "ember_chorus",
    name: "Ember Chorus",
    school: "shell",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 1,
    artSubject: "cracked ceramic choir figure ember eyes bone shrine coastal dusk",
    text: "Revelation: Gain 1 Sight per Vessel you control (max 2). Witnessed: +1 Sight/turn.",
  },
  {
    id: "sunset_creditor",
    name: "Sunset Creditor",
    school: "deal",
    type: "figure",
    essence: 4,
    witnessCost: 2,
    veiledPower: 3,
    witnessedPower: 5,
    sightYield: 0,
    artSubject: "jackal-mask creditor ledger staff canyon sunset purple coat gold seals",
    text: "Revelation: Gain 1 Eclipse. If you already had Eclipse, draw 1.",
    premium: true,
  },
  {
    id: "ochre_dancer",
    name: "Ochre Dancer",
    school: "cube",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject:
      "elegant ochre-veiled dancer geometric cube-mask teal sash desert cliff banners beauty with ritual wrongness",
    text: "Revelation: If you control Veil Banner, draw 1.",
  },
  {
    id: "bell_siren",
    name: "Bell Siren",
    school: "ring",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 4,
    sightYield: 1,
    artSubject:
      "alluring coastal cliff siren red parasol bells white banners eye seals wind-torn silk",
    text: "Revelation: Gain 1 Sight per Gaze altitude you control (max 2). Witnessed: +1 Sight/turn.",
  },
  {
    id: "moss_handmaid",
    name: "Moss Handmaid",
    school: "deep",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject:
      "graceful jungle handmaid moss crown waterfall stairs teal cloth multi-eye charms",
    text: "Revelation: If you control Abyss Cairn, draw 1.",
  },
  {
    id: "sail_widow",
    name: "Sail Widow",
    school: "graft",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject:
      "striking windmill widow sail-cloth dress cyan optics brass keys green hills",
    text: "Revelation: Gain 1 Sight. If you control a Graft Site, draw 1.",
  },
  {
    id: "cutwork_widow",
    name: "Cutwork Widow",
    school: "hollow",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 3,
    sightYield: 1,
    artSubject:
      "elegant hollow widow orange cloak circular cutouts bone mask barren pale arches",
    text: "Revelation: Blind Low this turn. Witnessed: +1 Sight/turn.",
  },
  {
    id: "ribbon_bride",
    name: "Ribbon Bride",
    school: "coral",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject:
      "coral-ribbon bride red branch-runes hanging ribbons arid pillars gold teal silk",
    text: "Revelation: If you control a Coral Site, gain 1 Sight.",
  },
  {
    id: "wick_oracle",
    name: "Wick Oracle",
    school: "shell",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject:
      "ceramic-wick oracle cracked porcelain beauty ember eye coastal bone shrine",
    text: "Revelation: Gain 1 Sight. If you have a Vessel in play, draw 1.",
  },
  {
    id: "shuttered_edict",
    name: "Shuttered Edict",
    school: "neutral",
    type: "prophecy",
    essence: 0,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "abstract shuttered law tablet sealed eye void ribbons floating shards",
    text: "Prophecy: On Pass, if any altitude is Blinded, gain 1 Eclipse.",
  },
  {
    id: "mask_gallery",
    name: "Mask Gallery",
    school: "many",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "tree-perch mask gallery twin faces hanging charms teal red banners",
    text: "Site. Your Stance B Figures here get +1 power.",
  },
  {
    id: "dusk_tithe",
    name: "Dusk Tithe",
    school: "deal",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "deal rite canyon dusk purple ledger ribbons gambling seals",
    text: "If you have Eclipse, draw 1. Otherwise Blind an altitude this turn.",
  },
  {
    id: "void_charm",
    name: "Void Charm",
    school: "hollow",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject: "hollow void charm circular cutout bone orange ribbon floating",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, Blind this altitude.",
  },
  {
    id: "iris_seal",
    name: "Iris Seal",
    school: "ring",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject: "rotating iris seal relic coastal gold teal parasol charms",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, if you have Gaze, gain 1 Sight.",
  },
  {
    id: "tide_singer",
    name: "Tide Singer",
    school: "shell",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "coastal shell singer cracked ceramic veil low-tide bone pillars",
    text: "Revelation: If you control Low-Tide Shrine, gain 1 Sight.",
  },
  {
    id: "millwright_colossus",
    name: "Millwright Colossus",
    school: "graft",
    type: "figure",
    essence: 5,
    witnessCost: 3,
    veiledPower: 3,
    witnessedPower: 6,
    sightYield: 0,
    artSubject: "immense windmill-graft colossus cyan optics brass sails green hills scale contrast",
    text: "Revelation: Draw 1. While Witnessed: your other Graft Figures have +1 power.",
    premium: true,
  },
  {
    id: "cutwork_sovereign",
    name: "Cutwork Sovereign",
    school: "hollow",
    type: "figure",
    essence: 4,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 5,
    sightYield: 2,
    artSubject: "hollow sovereign orange cutwork cloak bone crown barren pale arches void banners",
    text: "Revelation: Blind Mid this turn. Witnessed: +2 Sight/turn. This altitude has Gaze while Witnessed.",
    premium: true,
  },
  {
    id: "tablet_walker",
    name: "Tablet Walker",
    school: "coral",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject: "coral tablet walker red branch-runes arid pillars hanging ribbons stone seals",
    text: "Revelation: If you control another Coral card, gain 1 Eclipse.",
  },
  {
    id: "depth_bell",
    name: "Depth Bell",
    school: "deep",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "deep rite jungle bell moss cords waterfall teal seals",
    text: "Gain 1 Sight per Deep card you control (max 2).",
  },
  {
    id: "cube_charm",
    name: "Cube Charm",
    school: "cube",
    type: "relic",
    essence: 1,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject: "geometric cube charm teal ochre eye-glyph floating desert",
    text: "Graft: +1 power while host Witnessed. When host Witnesses on High, gain 1 Sight.",
  },
  {
    id: "gallery_debtor",
    name: "Gallery Debtor",
    school: "many",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "many-faced gallery debtor twin masks tree perch teal cloth charms",
    text: "Revelation: If you control Mask Gallery, draw 1.",
  },
  {
    id: "river_jack",
    name: "River Jack",
    school: "deal",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "jackal-mask river gambler purple coat canyon dusk ledger charms",
    text: "Revelation: If you control Dust Ledger, gain 1 Sight.",
  },
  {
    id: "bone_gallery",
    name: "Bone Gallery",
    school: "shell",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 1,
    artSubject: "coastal bone gallery cracked ceramic relics eye banners low tide",
    text: "Site. +1 Sight/turn. Your Witnessed Shell Figures here get +1 power.",
  },
  {
    id: "pillar_sovereign",
    name: "Pillar Sovereign",
    school: "coral",
    type: "figure",
    essence: 4,
    witnessCost: 2,
    veiledPower: 3,
    witnessedPower: 5,
    sightYield: 0,
    artSubject: "coral pillar sovereign red branch-rune crown arid tablets hanging ribbons gold",
    text: "Revelation: Gain 1 Eclipse per Coral Site you control (max 2).",
    premium: true,
  },
  {
    id: "ash_widow",
    name: "Ash Widow",
    school: "shell",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject: "ceramic ash widow cracked porcelain ember veil coastal bone shrine",
    text: "Revelation: If you control Bone Gallery, draw 1.",
  },
  {
    id: "ring_warden",
    name: "Ring Warden",
    school: "ring",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject: "coastal ring-temple warden rotating eye seal parasol path white banners",
    text: "Revelation: If you control a Gaze altitude, draw 1.",
  },
  {
    id: "stake_runner",
    name: "Stake Runner",
    school: "cube",
    type: "figure",
    essence: 1,
    witnessCost: 1,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 0,
    artSubject: "ochre stake-field runner geometric mask teal sash pale desert banners",
    text: "Revelation: Gain 1 Sight.",
  },
  {
    id: "splice_rite",
    name: "Splice Rite",
    school: "graft",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "graft rite windmill suture hands cyan optics brass charms",
    text: "If you control a Graft Site, gain 1 Sight. Otherwise Blind an altitude this turn.",
  },
  {
    id: "cataract_bell",
    name: "Cataract Bell",
    school: "deep",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject: "deep jungle bell-keeper moss cords waterfall multi-eye charms teal",
    text: "Revelation: If you control a Deep Site, gain 1 Sight.",
  },
  {
    id: "face_charm",
    name: "Face Charm",
    school: "many",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject: "twin-face wooden charm hanging chains teal cloth floating seal",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, switch its Stance.",
  },
  {
    id: "ember_sovereign",
    name: "Ember Sovereign",
    school: "shell",
    type: "figure",
    essence: 4,
    witnessCost: 2,
    veiledPower: 3,
    witnessedPower: 5,
    sightYield: 1,
    artSubject: "cracked ceramic ember sovereign bone crown coastal shrine scale glow eye seals",
    text: "Revelation: Gain 1 Sight per Vessel you control (max 2). While Witnessed: your other Shell Figures have +1 power.",
    premium: true,
  },
  {
    id: "arch_debtor",
    name: "Arch Debtor",
    school: "hollow",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 1,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "hollow arch debtor orange cutwork cloak pale barren stone arches",
    text: "Revelation: If you control Pale Arch, draw 1.",
  },
  {
    id: "horn_tithe",
    name: "Horn Tithe",
    school: "many",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "many rite horn chains twin masks teal red ribbons tree perch",
    text: "If you have a Stance B Figure, draw 1. Otherwise Blind an altitude this turn.",
  },
  {
    id: "stake_tithe",
    name: "Stake Tithe",
    school: "cube",
    type: "rite",
    essence: 1,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "cube rite ochre stakes pale sky eye-glyph banners ritual hands",
    text: "If you control a Cube Site, gain 1 Sight. Otherwise Blind Low this turn.",
  },
  {
    id: "parasol_debtor",
    name: "Parasol Debtor",
    school: "ring",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "coastal parasol debtor red silk bells white banners eye seals cliff path",
    text: "Revelation: If you control Parasol Path, gain 1 Sight.",
  },
  {
    id: "moss_charm",
    name: "Moss Charm",
    school: "deep",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject: "deep moss charm multi-eye gem waterfall teal floating seal",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, if you have a Deep Site, gain 1 Sight.",
  },
  {
    id: "key_debtor",
    name: "Key Debtor",
    school: "graft",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "graft key debtor brass oversized key cyan optics windmill hills",
    text: "Revelation: If you control a Graft Site, gain 1 Sight.",
  },
  {
    id: "mesa_bell",
    name: "Mesa Bell",
    school: "cube",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "ochre mesa bell-rung pilgrim cube-mask stake field cliff wind eye banners",
    text: "Revelation: If this is on High, gain 1 Sight.",
  },
  {
    id: "ledger_urn",
    name: "Ledger Urn",
    school: "deal",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject: "cracked purple ledger urn vessel coin-eye interior canyon sunset debt seals",
    text: "Vessel. Tucks a Figure from hand if able. Revelation: release Inhabitant here if empty, else to hand. If you have Eclipse, gain 1 Sight.",
  },
  {
    id: "horn_cantor",
    name: "Horn Cantor",
    school: "many",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "twin-horn cantor four-hole mask teal sash tree perch stance charms",
    text: "Revelation: If you have a Stance B Figure, gain 1 Sight.",
  },
  {
    id: "key_shrine",
    name: "Key Shrine",
    school: "graft",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 1,
    artSubject: "forest key shrine windmill-sail posts brass keys cyan optics green hills",
    text: "Site. +1 Sight/turn. Your Witnessed Graft Figures here get +1 power.",
  },
  {
    id: "pale_tithe",
    name: "Pale Tithe",
    school: "hollow",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "hollow pale tithe rite orange cutwork cloak barren arches void eye seal",
    text: "Blind Mid this turn. If you control Pale Arch, draw 1.",
  },
  {
    id: "coral_urn",
    name: "Coral Urn",
    school: "coral",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject: "coral-branch urn vessel red ribbons arid pillars teal silk eye glyphs",
    text: "Vessel. Tucks a Figure from hand if able. Revelation: release Inhabitant here if empty, else to hand. If you control a Coral Site, gain 1 Sight.",
  },
  {
    id: "gaze_tithe",
    name: "Gaze Tithe",
    school: "ring",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "ring gaze tithe rite red parasol coastal cliffs rotating eye seal bells",
    text: "If you control a Gaze altitude, draw 1. Otherwise Blind an altitude this turn.",
  },
  {
    id: "low_runner",
    name: "Low Runner",
    school: "cube",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "ochre low-road runner cube-mask stake path canyon floor eye banners",
    text: "Revelation: If this is on Low, draw 1.",
  },
  {
    id: "dusk_charm",
    name: "Dusk Charm",
    school: "deal",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject: "purple dusk coin-charm eclipse seal canyon sunset hanging ofuda",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, if you have Eclipse, Blind that altitude.",
  },
  {
    id: "mask_urn",
    name: "Mask Urn",
    school: "many",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject: "twin-face mask urn vessel four-hole charms teal cloth tree perch forest",
    text: "Vessel. Tucks a Figure from hand if able. Revelation: release Inhabitant here if empty, else to hand. If you have a Stance B Figure, gain 1 Sight.",
  },
  {
    id: "sail_runner",
    name: "Sail Runner",
    school: "graft",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "patchwork sail-runner windmill cloth cyan lenses brass key belt green hills",
    text: "Revelation: If you control another Graft Figure, gain 1 Sight.",
  },
  {
    id: "void_gallery",
    name: "Void Gallery",
    school: "hollow",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 1,
    artSubject: "hollow void gallery barren pale arches orange cutwork banners void yellow sky",
    text: "Site. +1 Sight/turn. Your Veiled Hollow Figures here get +1 power.",
  },
  {
    id: "mire_urn",
    name: "Mire Urn",
    school: "deep",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject: "deep mire urn vessel blue-green glaze multi-eye seal jungle ruins waterfall gems",
    text: "Vessel. Tucks a Figure from hand if able. Revelation: release Inhabitant here if empty, else to hand. If you control a Deep Site, gain 1 Sight.",
  },
  {
    id: "ember_tithe",
    name: "Ember Tithe",
    school: "shell",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "shell ember tithe rite cracked ceramic wick-flame bone pillars coastal shrine",
    text: "Blind an altitude this turn. If you have a Vessel in play, draw 1.",
  },
  {
    id: "mid_runner",
    name: "Mid Runner",
    school: "cube",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "ochre mid-terrace runner cube-mask stake causeway cliff ledge eye banners noon sky",
    text: "Revelation: If this is on Mid, gain 1 Sight.",
  },
  {
    id: "iris_urn",
    name: "Iris Urn",
    school: "ring",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject: "ring iris urn-vessel rotating brass eye-seal red parasol coastal cliff shrine bells",
    text: "Vessel. Tucks a Figure from hand if able. Revelation: release Inhabitant here if empty, else to hand. If you control a Gaze altitude, gain 1 Sight.",
  },
  {
    id: "pillar_cache",
    name: "Pillar Cache",
    school: "coral",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 1,
    artSubject: "arid coral pillar cache red branch-runes hanging ribbons tablet niches teal silk mid terrace",
    text: "Site. +1 Sight/turn. When you Witness a Coral Figure here, gain 1 Sight.",
  },
  {
    id: "key_cantor",
    name: "Key Cantor",
    school: "graft",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "graft key-cantor windmill-cloth cloak oversized brass keys cyan lenses mid causeway forest hills",
    text: "Revelation: If this is on Mid and you control a Graft Site, gain 1 Sight.",
  },
  {
    id: "dusk_cantor",
    name: "Dusk Cantor",
    school: "deal",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "purple dusk cantor jackal-coin mask ledger sash mid canyon terrace eclipse sunset ofuda",
    text: "Revelation: If this is on Mid and you have Eclipse, draw 1.",
  },
  {
    id: "arch_urn",
    name: "Arch Urn",
    school: "hollow",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject: "hollow arch urn-vessel orange cutwork barren pale arches void-yellow sky perforated lid",
    text: "Vessel. Tucks a Figure from hand if able. Revelation: release Inhabitant here if empty, else to hand. If you control a Hollow Site, gain 1 Sight.",
  },
  {
    id: "cairn_tithe",
    name: "Cairn Tithe",
    school: "deep",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "deep cairn tithe moss-stone offering multi-eye seal jungle ruin waterfall gem glow",
    text: "If you control a Deep Site, draw 1. Otherwise Blind an altitude this turn.",
  },
  {
    id: "stake_urn",
    name: "Stake Urn",
    school: "cube",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject: "cube stake urn-vessel geometric seal desert cliff terrace eye banners ochre stakes",
    text: "Vessel. Tucks a Figure from hand if able. Revelation: release Inhabitant here if empty, else to hand. If you control a Cube Site, gain 1 Sight.",
  },
  {
    id: "splice_urn",
    name: "Splice Urn",
    school: "graft",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject: "graft splice urn brass-key lid windmill cloth cyan optics forest shrine green hills",
    text: "Vessel. Tucks a Figure from hand if able. Revelation: release Inhabitant here if empty, else to hand. If you control a Graft Site, gain 1 Sight.",
  },
  {
    id: "ribbon_runner",
    name: "Ribbon Runner",
    school: "coral",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "coral ribbon runner red branch-rune sash arid mid terrace hanging ribbons teal silk",
    text: "Revelation: If this is on Mid and you control a Coral Site, gain 1 Sight.",
  },
  {
    id: "horn_runner",
    name: "Horn Runner",
    school: "many",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "many horn runner twin-horn four-hole mask teal sash mid tree causeway stance charms",
    text: "Revelation: If this is on Mid and you have a Stance B Figure, draw 1.",
  },
  {
    id: "wick_cantor",
    name: "Wick Cantor",
    school: "shell",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "shell wick cantor cracked ceramic mask bone pillars coastal mid shrine candle flame",
    text: "Revelation: If this is on Mid and you have a Vessel in play, gain 1 Sight.",
  },
  {
    id: "mire_gallery",
    name: "Mire Gallery",
    school: "deep",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 1,
    artSubject: "deep mire gallery jungle ruin arches multi-eye seals waterfall mist gem glow veiled niches",
    text: "Site. +1 Sight/turn. Your Veiled Deep Figures here get +1 power.",
  },
  {
    id: "coral_charm",
    name: "Coral Charm",
    school: "coral",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject: "coral branch charm red ribbon knot arid pillar tablet teal silk hanging ofuda",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, if you control a Coral Site, gain 1 Sight.",
  },
  {
    id: "parasol_runner",
    name: "Parasol Runner",
    school: "ring",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "ring parasol runner red parasol mid cliff path rotating eye seal bells coastal wind",
    text: "Revelation: If this is on Mid and you control a Gaze altitude, gain 1 Sight.",
  },
  {
    id: "dust_cache",
    name: "Dust Cache",
    school: "deal",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 1,
    artSubject: "deal dust cache canyon ledger shelves coin-eye seals purple dusk ofuda mid terrace",
    text: "Site. +1 Sight/turn. When you Witness a Deal Figure here, gain 1 Sight.",
  },
  {
    id: "pale_runner",
    name: "Pale Runner",
    school: "hollow",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "hollow pale runner orange cutwork cloak barren mid arches void-yellow sky perforated mask",
    text: "Revelation: If this is on Mid and you control a Hollow Site, gain 1 Sight.",
  },
  {
    id: "mask_charm",
    name: "Mask Charm",
    school: "many",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject: "many mask charm four-hole ceramic twin-face teal sash tree perch hanging stance charms",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, if you have a Stance B Figure, gain 1 Sight.",
  },
  {
    id: "wick_charm",
    name: "Wick Charm",
    school: "shell",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject: "shell wick charm cracked ceramic candle bone pillar coastal shrine warm ash light",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, if you have a Vessel in play, gain 1 Sight.",
  },
  {
    id: "cataract_runner",
    name: "Cataract Runner",
    school: "deep",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "deep cataract runner moss cords multi-eye charms mid jungle bridge waterfall gem glow",
    text: "Revelation: If this is on Mid and you control a Deep Site, gain 1 Sight.",
  },
  {
    id: "iris_charm",
    name: "Iris Charm",
    school: "ring",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject: "ring iris charm rotating brass eye-seal red parasol coastal cliffs hanging bells ofuda",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, if you control a Gaze altitude, gain 1 Sight.",
  },
];

const byId = new Map(CARDS.map((c) => [c.id, c]));

export function getCard(id: string): CardDef {
  const c = byId.get(id);
  if (!c) throw new Error(`Unknown card ${id}`);
  return c;
}

/** Curated Teach deck (default Play / First Gaze) — 30 cards, no premiums. */
export function teachDeck(): string[] {
  return [
    "cliff_seeker",
    "cliff_seeker",
    "veil_banner",
    "stake_field_pilgrim",
    "ace_of_hollows",
    "hatline_trickster",
    "third_face",
    "echo_mask",
    "root_chassis",
    "keywright_scarecrow",
    "hole_choir",
    "pale_silence",
    "coral_crown",
    "branch_rune_reliquary",
    "ash_lantern",
    "bone_wick_charm",
    "parasol_path",
    "perforated_abbess",
    "ring_gaze",
    "bell_debt_walker",
    "mire_debtor",
    "ledger_jackal",
    "inkdrip_acolyte",
    "canister_hound",
    "ribbon_bride",
    "saltglass_courier",
    "unblinking_law",
    "stake_cache",
    "mesa_bell",
    "horn_cantor",
  ];
}

/** @deprecated Use teachDeck() — alias for older call sites. */
export function starterDeck(): string[] {
  return teachDeck();
}

export function schoolColor(school: CardDef["school"]): [number, number, number] {
  switch (school) {
    case "cube":
      return [0.55, 0.42, 0.28];
    case "deal":
      return [0.42, 0.22, 0.55];
    case "many":
      return [0.35, 0.45, 0.55];
    case "graft":
      return [0.25, 0.55, 0.38];
    case "hollow":
      return [0.55, 0.45, 0.15];
    case "coral":
      return [0.55, 0.2, 0.28];
    case "shell":
      return [0.75, 0.78, 0.82];
    case "deep":
      return [0.15, 0.35, 0.55];
    case "ring":
      return [0.45, 0.25, 0.65];
    default:
      return [0.5, 0.45, 0.55];
  }
}
