import type { CardDef } from "./types";

/**
 * Dusk Ledger — Wave 1 (Debt craft soft reboot).
 * Kit: gain / threshold / spend Eclipse; empty-Mid package. No Blind spine.
 */
export const DUSK_LEDGER_WAVE1: CardDef[] = [
  {
    id: "dusk_cantor",
    name: "Dusk Cantor",
    heresy: "deal",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject:
      "glamorous dusk cantor on canyon terrace at sunset, jackal-coin halfmask, copper-violet cloak, ledger sash with debt tags, eclipsed sun behind, copper charcoal ornate frame accents, original character",
    veiledAbility: "While Veiled: +1 power if you have Eclipse.",
    revelation: "If you have Eclipse, draw 1. If on Mid, gain 1 Sight.",
    text: "Veiled: While Veiled: +1 power if you have Eclipse. Revelation: If you have Eclipse, draw 1. If on Mid, gain 1 Sight.",
  },
  {
    id: "tithe_jackal",
    name: "Tithe Jackal",
    heresy: "deal",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject:
      "tithe jackal dusk pilgrim lean coyote-masked man copper coat, small coyote companion, canyon mid ledge, debt coin-eye seals, weathered canyon dusk, copper charcoal frame accents, original",
    veiledAbility: "When this wins Resolve while Veiled: if Mid has no enemy Figure, gain 1 Eclipse.",
    revelation: "If you have Eclipse, gain 1 Sight. If on Mid and no enemy Figure here, gain 1 Eclipse.",
    text: "Veiled: When this wins Resolve while Veiled: if Mid has no enemy Figure, gain 1 Eclipse. Revelation: If you have Eclipse, gain 1 Sight. If on Mid and no enemy Figure here, gain 1 Eclipse.",
  },
  {
    id: "holecloak_auditor",
    name: "Holecloak Auditor",
    heresy: "deal",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject:
      "holecloak auditor tall figure in perforated orange cutwork cloak with circular apertures like a sacred colander, ledger staff, canyon dusk void yellow-purple sky, eye seals, copper charcoal frame, original NOT hole choir copy",
    veiledAbility: "When this Holds: if you have no Eclipse, gain 1 Eclipse.",
    revelation: "If you have Eclipse, draw 1 and gain 1 Sight. Otherwise gain 1 Eclipse.",
    text: "Veiled: When this Holds: if you have no Eclipse, gain 1 Eclipse. Revelation: If you have Eclipse, draw 1 and gain 1 Sight. Otherwise gain 1 Eclipse.",
  },
  {
    id: "amber_widow",
    name: "Amber Widow",
    heresy: "deal",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject:
      "glamorous sexy amber widow in copper veil with coin tears, canyon sunset beauty and wrongness, ledger jewelry, amber silk and charcoal dusk, original character",
    veiledAbility: "When this wins Resolve while Veiled: if the opponent has Eclipse, gain 1 Eclipse.",
    revelation: "If the opponent has Eclipse, gain 1 Eclipse. If you have Eclipse, draw 1.",
    text: "Veiled: When this wins Resolve while Veiled: if the opponent has Eclipse, gain 1 Eclipse. Revelation: If the opponent has Eclipse, gain 1 Eclipse. If you have Eclipse, draw 1.",
  },
  {
    id: "windkey_courier",
    name: "Windkey Courier",
    heresy: "deal",
    type: "figure",
    essence: 1,
    witnessCost: 1,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 0,
    artSubject:
      "small comic sly windkey courier youth with oversized brass key and satchel, sprinting canyon path at dusk, copper scarf, playful silhouette, copper charcoal accents, original",
    veiledAbility: "When this Holds: if Mid has no enemy Figure, gain 1 Sight.",
    revelation: "Gain 1 Sight. If Mid has no enemy Figure, gain 1 Eclipse.",
    text: "Veiled: When this Holds: if Mid has no enemy Figure, gain 1 Sight. Revelation: Gain 1 Sight. If Mid has no enemy Figure, gain 1 Eclipse.",
  },
  {
    id: "eclipse_sovereign",
    name: "Eclipse Sovereign",
    heresy: "deal",
    type: "figure",
    essence: 5,
    witnessCost: 3,
    veiledPower: 3,
    witnessedPower: 6,
    sightYield: 0,
    sovereign: true,
    artSubject:
      "eclipse sovereign majestic on dusk canyon throne, copper crown, eclipsed sun halo, ledger banners and debt coins, regal silhouette, premium copper charcoal ornate frame, original",
    text: "Revelation: Gain 1 Eclipse. Fall: draw 1. While Witnessed: if you have Eclipse, your Dusk Ledger Figures have +1 power.",
  },
  {
    id: "coin_gallery",
    name: "Coin Gallery",
    heresy: "deal",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 1,
    artSubject:
      "canyon coin gallery copper charcoal shelves floating debt-coins hanging ofuda dusk sky landmark original",
    text: "Site. +1 Sight/turn. When you Witness a Dusk Ledger Figure here, if you have Eclipse, draw 1.",
  },
  {
    id: "empty_mesa",
    name: "Empty Mesa",
    heresy: "deal",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject:
      "empty mesa canyon mid terrace wind-key stones barren dusk copper dust landmark original",
    text: "Site. Your Figures here have +1 power while you have Eclipse. When you Witness a Figure here, if Mid has no enemy Figure, gain 1 Eclipse.",
  },
  {
    id: "dusk_seal",
    name: "Dusk Seal",
    heresy: "deal",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject:
      "dusk seal eclipse-coin relic copper brass rim canyon sunset hanging charm original",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, if you have Eclipse, draw 1.",
  },
  {
    id: "debt_coin",
    name: "Debt Coin",
    heresy: "deal",
    type: "relic",
    essence: 1,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject:
      "debt coin two-face eclipse copper coin charm ledger cord canyon dusk original",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, if you have Eclipse, gain 1 Sight.",
  },
  {
    id: "creditor_tithe",
    name: "Creditor Tithe",
    heresy: "deal",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject:
      "creditor tithe rite copper staff canyon ledger dusk eclipse coin seals original",
    text: "If you have Eclipse, draw 1 and gain 1 Sight. Otherwise gain 1 Eclipse.",
  },
  {
    id: "settle_accounts",
    name: "Settle Accounts",
    heresy: "deal",
    type: "rite",
    essence: 1,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject:
      "settle accounts rite closing ledger stamp copper ink canyon dusk original",
    text: "Pay 1 Eclipse: draw 1. If you cannot, gain 1 Sight.",
  },
  {
    id: "jackal_urn",
    name: "Jackal Urn",
    heresy: "deal",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject:
      "jackal-mask ledger urn vessel copper gold coin-eye interior canyon dusk debt seals original",
    text: "Vessel. Tucks a Figure from hand if able. Fall: release Inhabitant here. Revelation: release Inhabitant here if empty, else to hand. If you have Eclipse, gain 1 Sight.",
  },
];

export const DUSK_LEDGER_WAVE1_RITE_IDS = new Set(["creditor_tithe", "settle_accounts"]);
