import type { CardDef } from "./types";

/** Motley Masquerade — Wave 2 (shelved; old Stance set until rebuilt). */
export const MOTLEY_COURT_WAVE2: CardDef[] = [
  {
    id: "mirrored_jester",
    name: "Mirrored Jester",
    heresy: "motley",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject: "motley mirrored jester split reflection purple teal cliffs original",
    text: "Revelation: Switch Stance. If Stance B after, gain 1 Sight. If an enemy Figure here is Veiled, gain 1 Favor.",
  },
  {
    id: "chance_step_dancer",
    name: "Chance-Step Dancer",
    heresy: "motley",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 1,
    witnessedPower: 3,
    sightYield: 1,
    artSubject: "glamorous sexy motley chance-step dancer dice stairs purple teal cliffs original",
    text: "Revelation: Enter Stance B. If you control a Motley Site, gain 2 Sight. Witnessed: +1 Sight/turn.",
  },
  {
    id: "twin_coin_bailiff",
    name: "Twin-Coin Bailiff",
    heresy: "motley",
    type: "figure",
    essence: 4,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 5,
    sightYield: 0,
    artSubject: "motley twin-coin bailiff gold medals purple court plaza original",
    text: "Revelation: Switch Stance on each other friendly Figure. Gain 1 Sight for each that entered Stance B (max 2).",
  },
  {
    id: "borrowed_face_urn",
    name: "Borrowed-Face Urn",
    heresy: "motley",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 3,
    sightYield: 0,
    artSubject: "motley borrowed-face urn smile spiral clay vessel original",
    text: "Vessel. Revelation: Enter Stance B. If Stance B after, gain 1 Sight. Fall: If Stance B, gain 1 Sight.",
  },
  {
    id: "grinning_colonnade",
    name: "Grinning Colonnade",
    heresy: "motley",
    type: "site",
    essence: 3,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "motley grinning colonnade smile pillars cliff amphitheater original",
    text: "Site. Your Stance B Figures here have +2 power. When you switch Stance on a Figure here, gain 1 Sight.",
  },
  {
    id: "harlequin_sash",
    name: "Harlequin Sash",
    heresy: "motley",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject: "motley harlequin sash purple teal gold cloth relic original",
    text: "Graft: +1 power while host Witnessed. When host switches Stance, gain 1 Sight. If host entered Stance B, also gain 1 Sight.",
  },
  {
    id: "echo_the_flip",
    name: "Echo the Flip",
    heresy: "motley",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "motley echo the flip ripple second card rite original",
    text: "Switch Stance on a friendly Figure. If it became Stance B, switch Stance on another friendly Figure. If both are Stance B after, gain 1 Sight.",
  },
  {
    id: "curtain_call",
    name: "Curtain Call",
    heresy: "motley",
    type: "rite",
    essence: 1,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject: "motley curtain call stage curtains amphitheater rite original",
    text: "If you have a Stance B Figure, gain 1 Favor; if you have 2+, also gain 1 Sight. Otherwise gain 1 Sight.",
  },
];

export const MOTLEY_COURT_WAVE2_RITE_IDS = new Set(["echo_the_flip", "curtain_call"]);
