import type { CardDef } from "./types";

/**
 * Waves 17–25 — Heresy Seals (5 cards × 9 heresies).
 * Each package is verb-locked: swapping a card into another heresy should break its payoff.
 * Art subjects are unique silhouettes/environments per card (procedural until full-face ships).
 */
export const WAVE_HERESY_SEALS: CardDef[] = [
  // ——— Wave 17 · Ashlar Veil (Hold) ———
  {
    id: "ochre_warden",
    name: "Ochre Warden",
    heresy: "cube",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject:
      "ochre stake warden geometric four-hole mask teal sash barren cliff mast companion hound pale desert banners",
    text: "Revelation: If on Low and you control another Veiled Figure, gain 1 Sight.",
  },
  {
    id: "stake_mast",
    name: "Stake Mast",
    heresy: "cube",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject:
      "tall stake mast eye-glyph banners rope bridges barren field pale ochre sky geometric seals",
    text: "Site. Your Veiled Figures here get +1 power. When you Witness an Ashlar Figure here, if you control another Veiled Figure, gain 1 Sight.",
  },
  {
    id: "banner_charm",
    name: "Banner Charm",
    heresy: "cube",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject:
      "miniature veil-banner charm teal cloth eye-in-circle seal hanging ofuda desert wind",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, if you control Veil Banner, gain 1 Sight.",
  },
  {
    id: "hold_tithe",
    name: "Hold Tithe",
    heresy: "cube",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject:
      "ashlar hold tithe rite geometric mask staff barren stakes teal sash pale sky eye seals",
    text: "If you control Veil Banner, gain 1 Sight. Otherwise Blind Low this turn.",
  },
  {
    id: "mesa_urn",
    name: "Mesa Urn",
    heresy: "cube",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject:
      "ochre mesa urn-vessel geometric lid eye-glyph interior cliff terrace pale banners",
    text: "Vessel. Tucks a Figure from hand if able. Fall: release Inhabitant here. Revelation: release Inhabitant here if empty, else to hand. If you control an Ashlar Site or a Veiled Figure, gain 1 Sight.",
  },

  // ——— Wave 19 · Facet Host (Stance) ———
  {
    id: "twin_debtor",
    name: "Twin Debtor",
    heresy: "many",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject:
      "twin-face debtor four-hole masks horn chain teal sash tree perch hanging stance charms",
    text: "Revelation: Switch Stance on this Figure. If it is Stance B after, gain 1 Sight.",
  },
  {
    id: "facet_shrine",
    name: "Facet Shrine",
    heresy: "many",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject:
      "facet shrine split-mask plaques tree perch teal red cloth hanging charms twin horns",
    text: "Site. When you switch Stance on a Figure here, gain 1 Sight.",
  },
  {
    id: "stance_charm",
    name: "Stance Charm",
    heresy: "many",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject:
      "stance charm twin ceramic faces horn-ring teal ribbon tree-perch seals floating",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, switch its Stance. If it is Stance B after, gain 1 Sight.",
  },
  {
    id: "facet_tithe",
    name: "Facet Tithe",
    heresy: "many",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject:
      "facet tithe rite twin-mask staff tree canopy teal cloth hanging charms stance seals",
    text: "If you have a Stance B Figure, gain 1 Sight. Otherwise Blind an altitude this turn.",
  },
  {
    id: "horn_urn",
    name: "Horn Urn",
    heresy: "many",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject:
      "horn-chain urn vessel twin-face lid teal sash tree perch stance charms hanging seals",
    text: "Vessel. Tucks a Figure from hand if able. Fall: release Inhabitant here. Revelation: release Inhabitant here if empty, else to hand. If you have a Stance B Figure, gain 1 Sight.",
  },

  // ——— Wave 20 · Keywright Join (Attach) ———
  {
    id: "brass_hound",
    name: "Brass Hound",
    heresy: "graft",
    type: "figure",
    essence: 2,
    witnessCost: 1,
    veiledPower: 2,
    witnessedPower: 3,
    sightYield: 0,
    artSubject:
      "brass-optics hound patchwork sails cyan lenses windmill hills key-collar companion",
    text: "Revelation: If on Mid and this has a Graft, gain 1 Sight.",
  },
  {
    id: "sail_cache",
    name: "Sail Cache",
    heresy: "graft",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 1,
    artSubject:
      "windmill sail cache brass keys cyan optics green hills suture shelves hanging charms",
    text: "Site. +1 Sight/turn. When you Witness a Keywright Figure here that has a Graft, gain 1 Sight.",
  },
  {
    id: "mill_charm",
    name: "Mill Charm",
    heresy: "graft",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject:
      "miniature windmill charm brass key cyan lens green hill suture thread floating",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, if you control a Keywright Site, gain 1 Sight.",
  },
  {
    id: "key_tithe",
    name: "Key Tithe",
    heresy: "graft",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject:
      "keywright tithe rite oversized brass key cyan optics windmill hills suture sash",
    text: "If you control a Keywright Site, gain 1 Sight. Otherwise Blind an altitude this turn.",
  },
  {
    id: "windmill_urn",
    name: "Windmill Urn",
    heresy: "graft",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject:
      "windmill-sail urn vessel brass lid cyan optics green hills patchwork suture interior",
    text: "Vessel. Tucks a Figure from hand if able. Fall: release Inhabitant here. Revelation: release Inhabitant here if empty, else to hand. If you control a Keywright Site, gain 1 Sight.",
  },

  // ——— Wave 21 · Cutwork Pale (Blind) ———
  {
    id: "aperture_cantor",
    name: "Aperture Cantor",
    heresy: "hollow",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 3,
    sightYield: 1,
    artSubject:
      "aperture cantor orange cutwork cloak multi-hole bone mask barren pale arches void-yellow sky",
    text: "Revelation: Blind Mid this turn. Witnessed: +1 Sight/turn.",
  },
  {
    id: "cutwork_cache",
    name: "Cutwork Cache",
    heresy: "hollow",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 1,
    artSubject:
      "cutwork cache barren pale arches orange banners circular cutout shelves void-yellow sky",
    text: "Site. +1 Sight/turn. When you Witness a Cutwork Figure here, Blind High this turn.",
  },
  {
    id: "pale_charm",
    name: "Pale Charm",
    heresy: "hollow",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject:
      "pale cutwork charm circular bone aperture orange ribbon barren arch floating seal",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, Blind Low this turn.",
  },
  {
    id: "aperture_tithe",
    name: "Aperture Tithe",
    heresy: "hollow",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject:
      "aperture tithe rite orange cutwork cloak barren arches void eye seal pale staff",
    text: "Blind High this turn. If you control Pale Arch, gain 1 Sight.",
  },
  {
    id: "void_urn",
    name: "Void Urn",
    heresy: "hollow",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject:
      "void urn vessel perforated lid orange cutwork barren pale arches void-yellow sky",
    text: "Vessel. Tucks a Figure from hand if able. Fall: release Inhabitant here. Revelation: release Inhabitant here if empty, else to hand. If you control a Cutwork Site, gain 1 Sight.",
  },

  // ——— Wave 22 · Branch-Rune (Colony) ———
  {
    id: "pillar_bride",
    name: "Pillar Bride",
    heresy: "coral",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject:
      "pillar bride red branch-rune veil arid stone columns hanging ribbons teal silk gold seals",
    text: "Revelation: If on Mid and you control 2+ Branch-Rune Sites, gain 1 Eclipse.",
  },
  {
    id: "ribbon_mast",
    name: "Ribbon Mast",
    heresy: "coral",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 1,
    artSubject:
      "ribbon mast arid pillar red branch-runes hanging ofuda teal cloth colony seals",
    text: "Site. +1 Sight/turn. Colony piece. When you Witness a Branch-Rune Figure here, gain 1 Sight.",
  },
  {
    id: "colony_charm",
    name: "Colony Charm",
    heresy: "coral",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject:
      "colony charm carved branch-knot red silk tassels arid pillar niches teal ofuda seals",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, gain 1 Sight per Branch-Rune Site you control (max 2).",
  },
  {
    id: "colony_tithe",
    name: "Colony Tithe",
    heresy: "coral",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject:
      "colony tithe rite red branch-rune staff arid pillars hanging ribbons teal sash",
    text: "If you control a Branch-Rune Site, gain 1 Sight. Otherwise Blind an altitude this turn.",
  },
  {
    id: "tablet_urn",
    name: "Tablet Urn",
    heresy: "coral",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject:
      "tablet urn vessel red branch-rune lid arid pillars hanging ribbons teal silk eye glyphs",
    text: "Vessel. Tucks a Figure from hand if able. Fall: release Inhabitant here. Revelation: release Inhabitant here if empty, else to hand. If you control a Branch-Rune Site, gain 1 Sight.",
  },

  // ——— Wave 24 · Cataract Verdure (Chain) ———
  {
    id: "moss_walker",
    name: "Moss Walker",
    heresy: "deep",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject:
      "moss walker multi-eye charms jungle bridge waterfall teal cloth gem glow companion shade",
    text: "Revelation: If on Mid, gain 1 Sight. If you control a Veiled Figure, gain 1 additional Sight.",
  },
  {
    id: "cataract_cache",
    name: "Cataract Cache",
    heresy: "deep",
    type: "site",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 1,
    artSubject:
      "cataract cache jungle ruin shelves moss stones waterfall multi-eye seals gem glow",
    text: "Site. +1 Sight/turn. When you Witness a Cataract Figure here, if you control a Veiled Figure, gain 1 Sight.",
  },
  {
    id: "chain_charm",
    name: "Chain Charm",
    heresy: "deep",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject:
      "chain charm moss cords multi-eye seal waterfall gem floating jungle teal ribbon",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, if you control a Cataract Site and a Veiled Figure, gain 1 Sight.",
  },
  {
    id: "verdant_tithe",
    name: "Verdant Tithe",
    heresy: "deep",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject:
      "verdant tithe rite moss staff jungle waterfall multi-eye seal teal cloth gem glow",
    text: "Gain 1 Sight per Cataract card you control (max 2). If you control none, Blind an altitude this turn.",
  },
  {
    id: "abyss_urn",
    name: "Abyss Urn",
    heresy: "deep",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject:
      "abyss cairn urn vessel moss lid jungle ruin waterfall multi-eye interior gem glow",
    text: "Vessel. Tucks a Figure from hand if able. Fall: release Inhabitant here. Revelation: release Inhabitant here if empty, else to hand. If you control a Cataract Site, gain 1 Sight. If you control a Veiled Figure, gain 1 additional Sight.",
  },

  // ——— Wave 25 · Iris Circle (Gaze) ———
  {
    id: "iris_cantor",
    name: "Iris Cantor",
    heresy: "ring",
    type: "figure",
    essence: 3,
    witnessCost: 2,
    veiledPower: 2,
    witnessedPower: 4,
    sightYield: 0,
    artSubject:
      "iris cantor rotating eye-seal red parasol coastal cliff white banners bells ofuda",
    text: "Revelation: If you control a Gaze altitude, gain 1 Sight. If an enemy is Veiled on a Gaze altitude, gain 1 Eclipse.",
  },
  {
    id: "circle_path",
    name: "Circle Path",
    heresy: "ring",
    type: "site",
    essence: 3,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 1,
    artSubject:
      "circle path rotating ring-eye waypoint coastal cliffs red parasol white banners bells",
    text: "Site with Gaze. +1 Sight/turn (+2 on High).",
  },
  {
    id: "heliograph_charm",
    name: "Heliograph Charm",
    heresy: "ring",
    type: "relic",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 1,
    sightYield: 0,
    artSubject:
      "heliograph charm rotating brass iris red parasol coastal sunlight seals hanging bells",
    text: "Graft: +1 power while host Witnessed. When host Witnesses, if you control a Gaze altitude, gain 1 Sight. If an enemy is Veiled on a Gaze altitude, gain 1 Eclipse.",
  },
  {
    id: "iris_tithe",
    name: "Iris Tithe",
    heresy: "ring",
    type: "rite",
    essence: 2,
    witnessCost: 0,
    veiledPower: 0,
    witnessedPower: 0,
    sightYield: 0,
    artSubject:
      "iris tithe rite red parasol coastal cliffs rotating eye seal white banners bells",
    text: "If you control a Gaze altitude, gain 1 Sight. Otherwise Blind High this turn.",
  },
  {
    id: "parasol_urn",
    name: "Parasol Urn",
    heresy: "ring",
    type: "vessel",
    essence: 3,
    witnessCost: 2,
    veiledPower: 1,
    witnessedPower: 2,
    sightYield: 1,
    artSubject:
      "parasol urn vessel red canopy lid rotating eye seal coastal cliffs white banners bells",
    text: "Vessel. Tucks a Figure from hand if able. Fall: release Inhabitant here. Revelation: release Inhabitant here if empty, else to hand. If you control a Gaze altitude, gain 1 Sight.",
  },
];

export const HERESY_SEALS_RITE_IDS = new Set([
  "hold_tithe",
  "facet_tithe",
  "key_tithe",
  "aperture_tithe",
  "colony_tithe",
  "verdant_tithe",
  "iris_tithe",
]);

export const HERESY_SEALS_VESSEL_IDS = [
  "mesa_urn",
  "horn_urn",
  "windmill_urn",
  "void_urn",
  "tablet_urn",
  "abyss_urn",
  "parasol_urn",
] as const;
